name: Git Checkout
description: Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
inputs:
  ref:
    description: The branch, tag or SHA to checkout. Default is the head of the default branch in the repository.
    required: false
    default: ${{ github.ref }}
  uploadCheckout:
    description: Upload the repo as-is for debug purposes. Default is to not upload.
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        ref: ${{ inputs.ref }}

    - if: inputs.uploadCheckout == 'true'
      name: Upload Repository
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: ${{ github.workspace }}
        include-hidden-files: true
branding:
  icon: 'umbrella'
  color: 'blue'
